### ISSUE TITLE
Apresentar nossa ideia para profissionais na área

### ISSUE THREAD

**Issue by Erickjonatthan** [Erickjonatthan/alfa-educa-web#2]

**Comment by ViniciusHenrykyy** [comment]
A entrevistada leciona para crianças do ensino fundamental e infantil e gostou bastante da ideia, ela colocou alguns pontos a serem feitos para que ela valide o aplicativo. ela sugeriu várias coisas, mas achou melhor eu não abordá-las pois não temos o aplicativo feito ainda e ela não sabe se vai poder ser feito. 

1- Ela disse que é importante que o aplicativo não substitua a interação humana nem a prática em sala, mas complementa o que ela ensina.
2- Ela acredita também que vai despertar mais o interesse por parte dos alunos que tem mais dificuldade em aprender.
3- Falou que seria interessante as cores do aplicativo serem bem intuitivas e coloridas para prender a atenção dos alunos do infantil.
4-  Ao finalizar o esqueleto do apk e site, disse que nos ajudaria a fazer as atividades que seriam destinadas as crianças.
5- Deixou claro que a medida que as atividades auxiliares do aplicativo fossem feitas ela se prontificaria a testar em sala de aula para ver se a atividade feita de fato tem efeito na aprendizagem.
